spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-handlers-package: com.homeputers.ebal2.api.mybatis.typehandler
  configuration:
    map-underscore-to-camel-case: true

ebal:
  otel:
    enabled: ${EBAL_OTEL_ENABLED:false}
    exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:}
  storage:
    enabled: ${EBAL_STORAGE_ENABLED:false}
    endpoint: ${EBAL_STORAGE_ENDPOINT:}
    access-key: ${EBAL_STORAGE_ACCESS_KEY:}
    secret-key: ${EBAL_STORAGE_SECRET_KEY:}
    bucket: ${EBAL_STORAGE_BUCKET:}
    region: ${EBAL_STORAGE_REGION:}
  seed:
    enabled: ${EBAL_SEED_ENABLED:false}
    admin:
      email: ${EBAL_SEED_ADMIN_EMAIL:admin@example.com}
      password: ${EBAL_SEED_ADMIN_PASSWORD:ChangeMe123!}
