spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-handlers-package: com.homeputers.ebal2.api.mybatis.typehandler
  configuration:
    map-underscore-to-camel-case: true

ebal:
  storage:
    enabled: ${EBAL_STORAGE_ENABLED:false}
    endpoint: ${EBAL_STORAGE_ENDPOINT:}
    access-key: ${EBAL_STORAGE_ACCESS_KEY:}
    secret-key: ${EBAL_STORAGE_SECRET_KEY:}
    bucket: ${EBAL_STORAGE_BUCKET:}
    region: ${EBAL_STORAGE_REGION:}
