spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-handlers-package: com.homeputers.ebal2.api.mybatis.typehandler
  configuration:
    map-underscore-to-camel-case: true

ebal:
  security:
    enabled: ${EBAL_SECURITY_ENABLED:true}
    cors:
      dev-origin: ${EBAL_WEB_ORIGIN_DEV:http://localhost:5173}
      prod-origin: ${EBAL_WEB_ORIGIN_PROD:}
    jwt:
      secret: ${EBAL_JWT_SECRET:ThisIsADefaultJwtSecretForLocalDevOnly_DoNotUseInProduction_ButItIsLongEnough1234}
      access-token-ttl: ${EBAL_JWT_ACCESS_TTL:PT15M}
      refresh-token-ttl: ${EBAL_JWT_REFRESH_TTL:P30D}
    password-reset:
      ttl: ${EBAL_PASSWORD_RESET_TTL:PT1H}
  profile:
    avatar:
      storage-path: ${EBAL_PROFILE_AVATAR_PATH:uploads/avatars}
      public-base-url: ${EBAL_PROFILE_AVATAR_BASE_URL:/static/avatars/}
      max-size-bytes: ${EBAL_PROFILE_AVATAR_MAX_SIZE:2097152}
    email-change:
      ttl: ${EBAL_PROFILE_EMAIL_CHANGE_TTL:PT1H}
    rate-limit:
      max-attempts: ${EBAL_PROFILE_RATE_LIMIT_MAX:5}
      window: ${EBAL_PROFILE_RATE_LIMIT_WINDOW:PT5M}
  mail:
    frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
    smtp:
      enabled: ${EBAL_MAIL_SMTP_ENABLED:false}
      host: ${EBAL_MAIL_SMTP_HOST:}
      port: ${EBAL_MAIL_SMTP_PORT:587}
      username: ${EBAL_MAIL_SMTP_USERNAME:}
      password: ${EBAL_MAIL_SMTP_PASSWORD:}
      start-tls: ${EBAL_MAIL_SMTP_STARTTLS:true}
      auth: ${EBAL_MAIL_SMTP_AUTH:true}
      from-address: ${EBAL_MAIL_FROM:no-reply@example.com}
  otel:
    enabled: ${EBAL_OTEL_ENABLED:false}
    exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:}
  storage:
    enabled: ${EBAL_STORAGE_ENABLED:false}
    endpoint: ${EBAL_STORAGE_ENDPOINT:}
    access-key: ${EBAL_STORAGE_ACCESS_KEY:}
    secret-key: ${EBAL_STORAGE_SECRET_KEY:}
    bucket: ${EBAL_STORAGE_BUCKET:}
    region: ${EBAL_STORAGE_REGION:}
  seed:
    enabled: ${EBAL_SEED_ENABLED:false}
    admin:
      email: ${EBAL_SEED_ADMIN_EMAIL:admin@example.com}
      password: ${EBAL_SEED_ADMIN_PASSWORD:ChangeMe123!}
