version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: apps/api-java/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "4173:80"
    depends_on:
      - api

  # nginx:
  #   image: nginx:1.25-alpine
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web
  #     - api

volumes:
  postgres_data:
