version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ebal
      POSTGRES_USER: ebal
      POSTGRES_PASSWORD: ebal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
