name: API CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run unit tests
        working-directory: apps/api-java
        run: ./mvnw -B test

      - name: Run Maven verify
        working-directory: apps/api-java
        run: ./mvnw -B -DskipTests=false verify
